
//lib/templates.ts
export interface Template {
  id: string
  name: string
  description: string
  style: string
  category: "minimal" | "modern" | "creative" | "professional" | "bold"
  tags: string[]
  thumbnail: string
  previewUrl?: string
  features: string[]
  colorScheme: "light" | "dark" | "mixed"
  layout: "single-page" | "multi-section" | "grid-based" | "timeline"
}

export const TEMPLATES: Template[] = [
  {
    id: "nebula-minimal",
    name: "Nebula Minimal",
    description: "Clean, airy design with serif headlines and muted palette for elegant simplicity",
    style: "Minimalist elegance with generous whitespace",
    category: "minimal",
    tags: ["Clean", "Serif", "Elegant", "Spacious"],
    thumbnail: "/minimal-portfolio-design-with-serif-typography.jpg",
    features: ["Serif typography", "Generous whitespace", "Muted color palette", "Clean layouts"],
    colorScheme: "light",
    layout: "single-page",
  },
  {
    id: "glass-aurora",
    name: "Glass Aurora",
    description: "Glassmorphism panels with gradient glows for a modern, translucent aesthetic",
    style: "Glassmorphism with gradient accents",
    category: "modern",
    tags: ["Glassmorphism", "Gradients", "Modern", "Translucent"],
    thumbnail: "/glassmorphism-portfolio-design-with-gradient-effec.jpg",
    features: ["Glass panels", "Gradient backgrounds", "Blur effects", "Modern aesthetics"],
    colorScheme: "mixed",
    layout: "multi-section",
  },
  {
    id: "card-grid-pro",
    name: "Card Grid Pro",
    description: "Masonry card layout perfect for showcasing diverse projects and achievements",
    style: "Dynamic masonry grid system",
    category: "modern",
    tags: ["Cards", "Grid", "Masonry", "Projects"],
    thumbnail: "/card-grid-portfolio-layout-with-masonry-design.jpg",
    features: ["Masonry layout", "Card-based design", "Project showcase", "Responsive grid"],
    colorScheme: "light",
    layout: "grid-based",
  },
  {
    id: "timeline-luxe",
    name: "Timeline Luxe",
    description: "Vertical timeline layout ideal for highlighting career progression and education",
    style: "Chronological timeline presentation",
    category: "professional",
    tags: ["Timeline", "Career", "Chronological", "Professional"],
    thumbnail: "/timeline-portfolio-design-with-career-progression.jpg",
    features: ["Vertical timeline", "Career focus", "Date markers", "Professional layout"],
    colorScheme: "light",
    layout: "timeline",
  },
  {
    id: "monochrome-bold",
    name: "Monochrome Bold",
    description: "High contrast black and white design that makes a powerful statement",
    style: "Bold monochromatic contrast",
    category: "bold",
    tags: ["Monochrome", "High Contrast", "Bold", "Statement"],
    thumbnail: "/monochrome-black-white-portfolio-design-high-contr.jpg",
    features: ["Black & white palette", "High contrast", "Bold typography", "Strong visual impact"],
    colorScheme: "mixed",
    layout: "single-page",
  },
  {
    id: "elegant-serif",
    name: "Elegant Serif",
    description: "Editorial-inspired design with large typography for content-focused portfolios",
    style: "Editorial magazine aesthetic",
    category: "professional",
    tags: ["Editorial", "Typography", "Content", "Magazine"],
    thumbnail: "/editorial-portfolio-design-with-large-serif-typogr.jpg",
    features: ["Large typography", "Editorial layout", "Content focus", "Reading experience"],
    colorScheme: "light",
    layout: "multi-section",
  },
  {
    id: "neon-deck",
    name: "Neon Deck",
    description: "Vibrant neon accents on dark background for creative and tech professionals",
    style: "Cyberpunk-inspired neon aesthetics",
    category: "creative",
    tags: ["Neon", "Dark", "Vibrant", "Tech"],
    thumbnail: "/neon-portfolio-design-with-vibrant-colors-on-dark-.jpg",
    features: ["Neon accents", "Dark theme", "Vibrant colors", "Tech aesthetic"],
    colorScheme: "dark",
    layout: "single-page",
  },
  {
    id: "soft-clay",
    name: "Soft Clay",
    description: "Neumorphism design with soft shadows and tactile button elements",
    style: "Neumorphic soft design language",
    category: "modern",
    tags: ["Neumorphism", "Soft", "Tactile", "Subtle"],
    thumbnail: "/neumorphism-portfolio-design-with-soft-shadows.jpg",
    features: ["Soft shadows", "Tactile elements", "Subtle depth", "Modern feel"],
    colorScheme: "light",
    layout: "multi-section",
  },
  {
    id: "metro-blocks",
    name: "Metro Blocks",
    description: "Colorful block-based design with strong grid system for organized content",
    style: "Metro-inspired block layout",
    category: "bold",
    tags: ["Blocks", "Colorful", "Grid", "Organized"],
    thumbnail: "/metro-blocks-portfolio-design-with-colorful-grid-l.jpg",
    features: ["Block layout", "Color coding", "Strong grid", "Organized sections"],
    colorScheme: "mixed",
    layout: "grid-based",
  },
  {
    id: "gradient-beam",
    name: "Gradient Beam",
    description: "Diagonal gradients and sleek lines for a futuristic, dynamic appearance",
    style: "Futuristic gradient aesthetics",
    category: "modern",
    tags: ["Gradients", "Diagonal", "Futuristic", "Dynamic"],
    thumbnail: "/gradient-beam-portfolio-with-diagonal-gradients-an.jpg",
    features: ["Diagonal gradients", "Sleek lines", "Dynamic layout", "Futuristic feel"],
    colorScheme: "mixed",
    layout: "single-page",
  },
  {
    id: "portfolio-scroll",
    name: "Portfolio Scroll",
    description: "Scroll-snapping sections for smooth navigation through portfolio content",
    style: "Smooth scroll-based navigation",
    category: "modern",
    tags: ["Scroll", "Smooth", "Navigation", "Sections"],
    thumbnail: "/scroll-portfolio-design-with-smooth-section-naviga.jpg",
    features: ["Scroll snapping", "Smooth transitions", "Section-based", "Interactive navigation"],
    colorScheme: "light",
    layout: "multi-section",
  },
  {
    id: "left-rail",
    name: "Left Rail",
    description: "Persistent left navigation rail for easy access to all portfolio sections",
    style: "Sidebar navigation layout",
    category: "professional",
    tags: ["Sidebar", "Navigation", "Persistent", "Professional"],
    thumbnail: "/left-rail-portfolio-design-with-sidebar-navigation.jpg",
    features: ["Left sidebar", "Persistent navigation", "Professional layout", "Easy access"],
    colorScheme: "light",
    layout: "multi-section",
  },
  {
    id: "hero-slider",
    name: "Hero Slider",
    description: "Cinematic hero carousel showcasing your best work with dramatic presentations",
    style: "Cinematic carousel presentation",
    category: "creative",
    tags: ["Carousel", "Cinematic", "Hero", "Dramatic"],
    thumbnail: "/hero-slider-portfolio-with-cinematic-carousel-desi.jpg",
    features: ["Hero carousel", "Cinematic feel", "Dramatic presentation", "Visual impact"],
    colorScheme: "mixed",
    layout: "single-page",
  },
  {
    id: "focus-resume",
    name: "Focus Resume",
    description: "Resume-centric layout optimized for traditional hiring processes and ATS systems",
    style: "Traditional resume-focused design",
    category: "professional",
    tags: ["Resume", "ATS", "Traditional", "Hiring"],
    thumbnail: "/resume-focused-portfolio-design-optimized-for-ats.jpg",
    features: ["Resume layout", "ATS optimized", "Traditional format", "Hiring focused"],
    colorScheme: "light",
    layout: "single-page",
  },
  {
    id: "showcase-gallery",
    name: "Showcase Gallery",
    description: "Project-first design with large imagery to highlight visual work and creativity",
    style: "Visual-first gallery layout",
    category: "creative",
    tags: ["Gallery", "Visual", "Projects", "Creative"],
    thumbnail: "/showcase-gallery-portfolio-with-large-project-imag.jpg",
    features: ["Large imagery", "Project focus", "Visual showcase", "Creative layout"],
    colorScheme: "light",
    layout: "grid-based",
  },
  {
    id: "tech-noir",
    name: "Tech Noir",
    description: "Dark, futuristic design perfect for developers and tech professionals",
    style: "Futuristic dark theme",
    category: "bold",
    tags: ["Dark", "Futuristic", "Tech", "Developer"],
    thumbnail: "/technoir.jpg",
    features: ["Dark theme", "Futuristic elements", "Tech aesthetic", "Developer focused"],
    colorScheme: "dark",
    layout: "single-page",
  },
  {
    id: "paper-craft",
    name: "Paper Craft",
    description: "Textured paper look with handcrafted feel for artistic and design portfolios",
    style: "Handcrafted paper aesthetic",
    category: "creative",
    tags: ["Paper", "Textured", "Handcrafted", "Artistic"],
    thumbnail: "/paper_craft.jpg",
    features: ["Paper texture", "Handcrafted feel", "Artistic design", "Unique aesthetic"],
    colorScheme: "light",
    layout: "multi-section",
  },
  {
    id: "rounded-cards",
    name: "Rounded Cards",
    description: "Playful rounded card design that creates a friendly, approachable portfolio",
    style: "Friendly rounded card system",
    category: "modern",
    tags: ["Rounded", "Playful", "Friendly", "Cards"],
    thumbnail: "/Rounded_portfolio.jpg",
    features: ["Rounded corners", "Playful design", "Friendly feel", "Card layout"],
    colorScheme: "light",
    layout: "grid-based",
  },
  {
    id: "clean-columns",
    name: "Clean Columns",
    description: "Newspaper-style column layout for content-heavy portfolios and writers",
    style: "Editorial column layout",
    category: "professional",
    tags: ["Columns", "Editorial", "Content", "Writers"],
    thumbnail: "/column_craft.jpg",
    features: ["Column layout", "Content focus", "Editorial style", "Reading optimized"],
    colorScheme: "light",
    layout: "multi-section",
  },
  {
    id: "studio-stack",
    name: "Studio Stack",
    description: "Agency-style design with sharp grids and professional presentation",
    style: "Agency-inspired grid system",
    category: "professional",
    tags: ["Agency", "Sharp", "Grid", "Professional"],
    thumbnail: "/studio.jpg",
    features: ["Sharp grids", "Agency style", "Professional feel", "Structured layout"],
    colorScheme: "light",
    layout: "grid-based",
  },
]

export const TEMPLATE_CATEGORIES = [
  { id: "all", label: "All Templates", count: TEMPLATES.length },
  { id: "minimal", label: "Minimal", count: TEMPLATES.filter((t) => t.category === "minimal").length },
  { id: "modern", label: "Modern", count: TEMPLATES.filter((t) => t.category === "modern").length },
  { id: "creative", label: "Creative", count: TEMPLATES.filter((t) => t.category === "creative").length },
  { id: "professional", label: "Professional", count: TEMPLATES.filter((t) => t.category === "professional").length },
  { id: "bold", label: "Bold", count: TEMPLATES.filter((t) => t.category === "bold").length },
]

export function getTemplateById(id: string): Template | undefined {
  return TEMPLATES.find((template) => template.id === id)
}

export function getTemplatesByCategory(category: string): Template[] {
  if (category === "all") return TEMPLATES
  return TEMPLATES.filter((template) => template.category === category)
}

export function getRandomTemplate(): Template {
  return TEMPLATES[Math.floor(Math.random() * TEMPLATES.length)]
}
